name: crow-frontend-pipeline-development

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_REPOSITORY_URL: ${{secrets.DOCKER_REPOSITORY_URL}}
  DOCKER_REPOSITORY_USER: ${{secrets.DOCKER_REPOSITORY_USER}}
  DOCKER_REPOSITORY_PASSWORD: ${{secrets.DOCKER_REPOSITORY_PASSWORD}}
  DOCKER_CONTAINER_NAME: web/app
  ENVIRONMENT_DOMAIN: https://crow-asfalt-impuls-tooling-web-test.azurewebsites.net/
  DOCKER_LATEST_IMAGE: test_latest

on:
  push:
    branches:
      - development

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: ./wd/workflow-repo      
      - name: Quasar Build Web
        shell: bash
        run: |
          file="./wd/workflow-repo/version_frontend.txt"
          while IFS= read line
          do
                  # display $line or do something with $line
            echo "$line"
          done <"$file"