name: crow-frontend-pipeline-development

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_REPOSITORY_URL: ${{secrets.DOCKER_REPOSITORY_URL}}
  DOCKER_REPOSITORY_USER: ${{secrets.DOCKER_REPOSITORY_USER}}
  DOCKER_REPOSITORY_PASSWORD: ${{secrets.DOCKER_REPOSITORY_PASSWORD}}
  DOCKER_LATEST_IMAGE: test_latest

on:
  push:
    branches:
      - development

jobs:
  frontend:
    runs-on: ubuntu-latest
    env:
      DOCKER_CONTAINER_NAME: web/app
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: ./wd/workflow-repo
      - name: Run read-yaml action
        id: frontend-version
        uses: KJ002/read-yaml@main # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: "./wd/workflow-repo/version_frontend.yml" # File to read from
          key-path: '["version"]' # Access the runs key then the using key and retuns the value.
      - name: Push to docker
        shell: bash
        run: |
          docker login ${{env.DOCKER_REPOSITORY_URL}} -u ${{env.DOCKER_REPOSITORY_USER}} -p ${{env.DOCKER_REPOSITORY_PASSWORD}}
          docker pull ${{env.DOCKER_REPOSITORY_URL}}/${{env.DOCKER_CONTAINER_NAME}}:${{steps.frontend-version.outputs.data}}
          docker tag ${{env.DOCKER_REPOSITORY_URL}}/${{env.DOCKER_CONTAINER_NAME}}:${{steps.frontend-version.outputs.data}} ${{env.DOCKER_REPOSITORY_URL}}/${{env.DOCKER_CONTAINER_NAME}}:${{env.DOCKER_LATEST_IMAGE}}
          docker push ${{env.DOCKER_REPOSITORY_URL}}/${{env.DOCKER_CONTAINER_NAME}}:${{env.DOCKER_LATEST_IMAGE}}
          docker logout ${{env.DOCKER_REPOSITORY_URL}}
