name: crow-frontend-pipeline-development

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_REPOSITORY_URL: ${{secrets.PRODUCTION_DOCKER_REPOSITORY_URL}}
  DOCKER_REPOSITORY_USER: ${{secrets.PRODUCTION_DOCKER_REPOSITORY_USER}}
  DOCKER_REPOSITORY_PASSWORD: ${{secrets.PRODUCTION_DOCKER_REPOSITORY_PASSWORD}}
  DOCKER_LATEST_IMAGE: latest

on:
  push:
    branches:
      - production

jobs:
  backend:
    runs-on: ubuntu-latest
    env:
      DOCKER_CONTAINER_NAME: web/api
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: ./wd/workflow-repo
      - name: Run read-yaml action
        id: frontend-version
        uses: KJ002/read-yaml@main
        with:
          file: "./wd/workflow-repo/version.yml"
          key-path: '["version", "backend"]'
      - name: Pull version from test registry
        shell: bash
        run: |
          docker login ${{secrets.TEST_DOCKER_REPOSITORY_URL}} -u ${{secrets.TEST_DOCKER_REPOSITORY_USER}} -p ${{secrets.TEST_DOCKER_REPOSITORY_PASSWORD}}
          docker pull ${{secrets.TEST_DOCKER_REPOSITORY_URL}}/${{env.DOCKER_CONTAINER_NAME}}:${{steps.frontend-version.outputs.data}}
          docker tag ${{secrets.TEST_DOCKER_REPOSITORY_URL}}/${{env.DOCKER_CONTAINER_NAME}}:${{steps.frontend-version.outputs.data}} ${{env.DOCKER_REPOSITORY_URL}}/${{env.DOCKER_CONTAINER_NAME}}:${{env.DOCKER_LATEST_IMAGE}}
          docker logout ${{secrets.TEST_DOCKER_REPOSITORY_URL}}
      - name: Push to production repository
        shell: bash
        run: |          
          docker login ${{env.DOCKER_REPOSITORY_URL}} -u ${{env.DOCKER_REPOSITORY_USER}} -p ${{env.DOCKER_REPOSITORY_PASSWORD}}
          docker push ${{env.DOCKER_REPOSITORY_URL}}/${{env.DOCKER_CONTAINER_NAME}}:${{env.DOCKER_LATEST_IMAGE}}
          docker logout ${{env.DOCKER_REPOSITORY_URL}}
  frontend:
    runs-on: ubuntu-latest
    env:
      DOCKER_CONTAINER_NAME: web/app
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: ./wd/workflow-repo
      - name: Run read-yaml action
        id: frontend-version
        uses: KJ002/read-yaml@main
        with:
          file: "./wd/workflow-repo/version.yml"
          key-path: '["version", "frontend"]'
      - name: Pull version from test registry
        shell: bash
        run: |
          docker login ${{secrets.TEST_DOCKER_REPOSITORY_URL}} -u ${{secrets.TEST_DOCKER_REPOSITORY_USER}} -p ${{secrets.TEST_DOCKER_REPOSITORY_PASSWORD}}
          docker pull ${{secrets.TEST_DOCKER_REPOSITORY_URL}}/${{env.DOCKER_CONTAINER_NAME}}:${{steps.frontend-version.outputs.data}}
          docker tag ${{secrets.TEST_DOCKER_REPOSITORY_URL}}/${{env.DOCKER_CONTAINER_NAME}}:${{steps.frontend-version.outputs.data}} ${{env.DOCKER_REPOSITORY_URL}}/${{env.DOCKER_CONTAINER_NAME}}:${{env.DOCKER_LATEST_IMAGE}}
          docker logout ${{secrets.TEST_DOCKER_REPOSITORY_URL}}
      - name: Push to production repository
        shell: bash
        run: |          
          docker login ${{env.DOCKER_REPOSITORY_URL}} -u ${{env.DOCKER_REPOSITORY_USER}} -p ${{env.DOCKER_REPOSITORY_PASSWORD}}
          docker push ${{env.DOCKER_REPOSITORY_URL}}/${{env.DOCKER_CONTAINER_NAME}}:${{env.DOCKER_LATEST_IMAGE}}
          docker logout ${{env.DOCKER_REPOSITORY_URL}}
  proxy:
    runs-on: ubuntu-latest
    env:
      DOCKER_CONTAINER_NAME: web/proxy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: ./wd/workflow-repo
      - name: Run read-yaml action
        id: frontend-version
        uses: KJ002/read-yaml@main
        with:
          file: "./wd/workflow-repo/version.yml"
          key-path: '["version", "proxy"]'
      - name: Pull version from test registry
        shell: bash
        run: |
          docker login ${{secrets.TEST_DOCKER_REPOSITORY_URL}} -u ${{secrets.TEST_DOCKER_REPOSITORY_USER}} -p ${{secrets.TEST_DOCKER_REPOSITORY_PASSWORD}}
          docker pull ${{secrets.TEST_DOCKER_REPOSITORY_URL}}/${{env.DOCKER_CONTAINER_NAME}}:${{steps.frontend-version.outputs.data}}
          docker tag ${{secrets.TEST_DOCKER_REPOSITORY_URL}}/${{env.DOCKER_CONTAINER_NAME}}:${{steps.frontend-version.outputs.data}} ${{env.DOCKER_REPOSITORY_URL}}/${{env.DOCKER_CONTAINER_NAME}}:${{env.DOCKER_LATEST_IMAGE}}
          docker logout ${{secrets.TEST_DOCKER_REPOSITORY_URL}}
      - name: Push to production repository
        shell: bash
        run: |          
          docker login ${{env.DOCKER_REPOSITORY_URL}} -u ${{env.DOCKER_REPOSITORY_USER}} -p ${{env.DOCKER_REPOSITORY_PASSWORD}}
          docker push ${{env.DOCKER_REPOSITORY_URL}}/${{env.DOCKER_CONTAINER_NAME}}:${{env.DOCKER_LATEST_IMAGE}}
          docker logout ${{env.DOCKER_REPOSITORY_URL}}